blank_issues_enabled: true
contact_links:
- name: Anything but bugs
  url: https://github.com/charmbracelet/{repo}/discussions/new/choose
  about: Please highlight your feature requests, questions, and feedback in discussions.
- name: Discord
  url: https://charm.sh/discord
  about: Hang out with the community!
