blank_issues_enabled: true
contact_links:
- name: Anything but bugs
  about: Please highlight your feature requests, questions, and feedback in discussions.
- name: Discord
  url: https://charm.sh/discord
  about: Hang out with the community!
